name: thesis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - jupyterlab
  - pip:
      - torch
      - transformers
      - tqdm
